### ISSUE TITLE
Plugin no longer working on latest update

### ISSUE THREAD

**Issue by jlintz** [logstash-plugins/logstash-output-nagios#3] opened 2015-09-22 18:40 UTC
I just updated all my plugins and filters to the latest versions

logstash-codec-collectd (1.0.1)
logstash-codec-dots (1.0.0)
logstash-codec-edn (1.0.0)
logstash-codec-edn_lines (1.0.0)
logstash-codec-es_bulk (1.0.0)
logstash-codec-fluent (1.0.0)
logstash-codec-graphite (1.0.0)
logstash-codec-json (1.1.0)
logstash-codec-json_lines (1.0.1)
logstash-codec-line (1.0.0)
logstash-codec-msgpack (1.0.0)
logstash-codec-multiline (1.0.0)
logstash-codec-netflow (1.0.0)
logstash-codec-oldlogstashjson (1.0.0)
logstash-codec-plain (1.0.0)
logstash-codec-rubydebug (1.0.0)
logstash-filter-anonymize (1.0.0)
logstash-filter-checksum (1.0.1)
logstash-filter-cidr (0.1.6)
logstash-filter-clone (1.0.0)
logstash-filter-csv (1.0.0)
logstash-filter-date (1.0.0)
logstash-filter-dns (1.0.0)
logstash-filter-drop (1.0.0)
logstash-filter-fingerprint (1.0.0)
logstash-filter-geoip (1.1.2)
logstash-filter-grok (1.0.0)
logstash-filter-json (1.0.1)
logstash-filter-kv (1.0.0)
logstash-filter-metrics (1.0.0)
logstash-filter-multiline (1.0.0)
logstash-filter-mutate (1.0.2)
logstash-filter-ruby (1.0.0)
logstash-filter-sleep (1.0.0)
logstash-filter-split (1.0.0)
logstash-filter-syslog_pri (1.0.1)
logstash-filter-throttle (1.0.0)
logstash-filter-urldecode (1.0.0)
logstash-filter-useragent (1.1.0)
logstash-filter-uuid (1.0.0)
logstash-filter-xml (1.0.0)
logstash-input-couchdb_changes (1.0.0)
logstash-input-elasticsearch (1.0.2)
logstash-input-eventlog (1.0.0)
logstash-input-exec (1.0.0)
logstash-input-file (1.0.1)
logstash-input-ganglia (1.0.0)
logstash-input-gelf (1.0.0)
logstash-input-generator (1.0.0)
logstash-input-graphite (1.0.0)
logstash-input-heartbeat (1.0.0)
logstash-input-http (1.0.3)
logstash-input-imap (1.0.0)
logstash-input-irc (1.0.0)
logstash-input-kafka (1.0.0)
logstash-input-log4j (1.0.0)
logstash-input-lumberjack (1.0.5)
logstash-input-pipe (1.0.0)
logstash-input-rabbitmq (1.1.1)
logstash-input-redis (1.0.3)
logstash-input-s3 (1.0.0)
logstash-input-snmptrap (1.0.0)
logstash-input-sqs (1.1.0)
logstash-input-stdin (1.0.0)
logstash-input-syslog (1.0.1)
logstash-input-tcp (1.0.0)
logstash-input-twitter (1.0.1)
logstash-input-udp (1.0.0)
logstash-input-unix (1.0.0)
logstash-input-xmpp (1.0.0)
logstash-input-zeromq (1.0.0)
logstash-output-cloudwatch (1.0.0)
logstash-output-csv (1.0.0)
logstash-output-elasticsearch (1.0.7)
logstash-output-elasticsearch_http (1.0.0)
logstash-output-email (2.0.0)
logstash-output-exec (1.0.0)
logstash-output-file (1.0.0)
logstash-output-ganglia (1.0.0)
logstash-output-gelf (1.1.0)
logstash-output-graphite (1.0.2)
logstash-output-hipchat (2.0.0)
logstash-output-http (1.1.0)
logstash-output-irc (1.0.0)
logstash-output-juggernaut (1.0.0)
logstash-output-kafka (1.0.0)
logstash-output-lumberjack (1.0.2)
logstash-output-nagios (1.1.0)
logstash-output-nagios_nsca (1.1.0)
logstash-output-null (1.0.1)
logstash-output-opentsdb (1.0.0)
logstash-output-pagerduty (1.0.0)
logstash-output-pipe (1.1.0)
logstash-output-rabbitmq (1.1.2)
logstash-output-redis (1.0.0)
logstash-output-s3 (1.0.0)
logstash-output-sns (2.0.1)
logstash-output-sqs (1.0.0)
logstash-output-statsd (1.1.0)
logstash-output-stdout (1.1.0)
logstash-output-tcp (1.0.0)
logstash-output-udp (1.1.0)
logstash-output-xmpp (1.0.0)
logstash-output-zeromq (1.0.0)

and now the nagios output seems to no longer work.  Failing with the following error

`{:timestamp=>"2015-09-22T14:31:02.525000-0400", :message=>"ping62.chartbeat.net~LOGSTASH~0~2015-09-22T18:30:56.824Z ping62.chartbeat.net", :error=>#<NameError: undefined local variable or method `message' for #<LogStash::Outputs::NagiosNsca:0x47c3b01f>>, :nagios_nsca_command=>"/usr/sbin/send_nsca -H nagios.chartbeat.com -p 5667 -d ~ -c /etc/send_nsca.cfg", :missed_event=>#<LogStash::Event:0x187a6569 @metadata={"retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0x6c706e1a @store={"message"=>" PING", "tags"=>["_jsonparsefailure", "_grokparsefailure"], "@version"=>"1", "@timestamp"=>"2015-09-22T18:30:56.824Z", "file"=>"/var/log/syslog", "host"=>"ping62.chartbeat.net", "offset"=>"26108098", "type"=>"syslog", "syslog_pri"=>"13", "logsource"=>"ping62", "program"=>"logstash_ping", "received_at"=>"2015-09-22T18:31:01.559Z", "syslog_severity_code"=>5, "syslog_facility_code"=>1, "syslog_facility"=>"user-level", "syslog_severity"=>"notice"}, @lut={"file"=>[{"message"=>" PING", "tags"=>["_jsonparsefailure", "_grokparsefailure"], "@version"=>"1", "@timestamp"=>"2015-09-22T18:30:56.824Z", "file"=>"/var/log/syslog", "host"=>"ping62.chartbeat.net", "offset"=>"26108098", "type"=>"syslog", "syslog_pri"=>"13", "logsource"=>"ping62", "program"=>"logstash_ping", "received_at"=>"2015-09-22T18:31:01.559Z", "syslog_severity_code"=>5, "syslog_facility_code"=>1, "syslog_facility"=>"user-level", "syslog_severity"=>"notice"}, "file"], "host"=>[{"mess`

I tried using the mutate filter to remove the message field and also change the `message_format` to not include %{message} but still got the same error

**Comment by tearsakura** [comment] 2015-11-04 08:17
Hi!, I'd upgrade to logstash 2.0.0 and get the same error.

**Comment by purbon** [comment] 2015-11-04 08:19
@jlintz @tearsakura can you share your configuration? 

@jlintz is `ping62.chartbeat.net~LOGSTASH~0~2015-09-22T18:30:56.824Z ping62.chartbeat.net`  line from your stack trace a good one to debug the issue? 

thanks a lot for your report.

**Comment by tearsakura** [comment] 2015-11-04 08:35
yep

nagios_nsca {
      host => "xxx.xxx.xxx.xxx"
      port => "5667"
      message_format => "%{ServiceName}"
      nagios_host => "NSCA_HOST"
      nagios_service => "NSCA_{{ env }}"
      send_nsca_config => "/etc/nagios/send_nsca.cfg"
      nagios_status => "%{nagios_status}"
    }

{:timestamp=>"2015-11-04T09:40:19.567000+0100", :message=>"NSCA_HOST~NSCA_pre~0~Everything OK!", :error=>#<NameError: undefined local variable or method `message' for #<LogStash::Outputs::NagiosNsca:0x34087d5f>>, :nagios_nsca_command=>"/usr/sbin/send_nsca -H xxx.xxx.xxx.xxx -p 5667 -d ~ -c /etc/nagios/send_nsca.cfg", :missed_event=>#<LogStash::Event:0x1048003c @metadata_accessors=#<LogStash::Util::Accessors:0x178403fd @store={"name"=>"consul_health", "host"=>"xxx.xxx.xxx.xxx", "request"=>{"headers"=>{"Accept"=>"application/json"}, "method"=>"get", "url"=>"http://xxx.xxx.xxx.xxx:8500/v1/health/state/critical"}, "runtime_seconds"=>0.294, "code"=>200, "response_headers"=>{"content-type"=>"application/json", "x-consul-index"=>"135473", "x-consul-knownleader"=>"true", "x-consul-lastcontact"=>"0", "date"=>"Wed, 04 Nov 2015 08:40:12 GMT", "content-length"=>"2"}, "response_message"=>"OK", "times_retried"=>0, "retry_count"=>0}, @lut={}>, @cancelled=false, @data={"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, @metadata={"name"=>"consul_health", "host"=>"xxx.xxx.xxx.xxx", "request"=>{"headers"=>{"Accept"=>"application/json"}, "method"=>"get", "url"=>"http://xxx.xxx.xxx.xxx:8500/v1/health/state/critical"}, "runtime_seconds"=>0.294, "code"=>200, "response_headers"=>{"content-type"=>"application/json", "x-consul-index"=>"135473", "x-consul-knownleader"=>"true", "x-consul-lastcontact"=>"0", "date"=>"Wed, 04 Nov 2015 08:40:12 GMT", "content-length"=>"2"}, "response_message"=>"OK", "times_retried"=>0, "retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0x25652d15 @store={"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, @lut={"[type]"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "type"], "nagios_status"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "nagios_status"], "source"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "source"], "[Status]"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "Status"], "duration"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "duration"], "threads_running"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "threads_running"], "threads_connected"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "threads_connected"], "environment"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "environment"], "timestamp"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "timestamp"], "type"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "type"], "[tags]"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "tags"], "ServiceName"=>[{"ServiceName"=>"Everything OK!", "@version"=>"1", "@timestamp"=>"2015-11-04T08:40:12.224Z", "type"=>"consul_health", "tags"=>["multiline"], "message"=>"", "nagios_status"=>"0", "source"=>"OK", "environment"=>"dev"}, "ServiceName"]}>>, :level=>:warn}

**Comment by purbon** [comment] 2015-11-04 08:42
Thanks @tearsakura, are you able to reproduce the same error with a minimal config, something like:

```
  input { stdin {} }
  output { your_nagios_config }
```

? I guess your other faces are not changing the event, isn't?

**Comment by tearsakura** [comment] 2015-11-04 09:07
I tried with :
 output { 
  nagios_nsca {
    host => "xxx.xxx.xxx.xx"
    port => "5667"
    message_format => "OK"
    nagios_host => "NSCA_HOST"
    nagios_service => "NSCA_pre"
    send_nsca_config => "/etc/nagios/send_nsca.cfg"
    nagios_status => 0
  }
}

and I get the same:

{:timestamp=>"2015-11-04T09:56:55.583000+0100", :message=>"NSCA_HOST~NSCA_pre~0~OK", :error=>#<NameError: undefined local variable or method `message' for #<LogStash::Outputs::NagiosNsca:0x5b50b55d>>, :nagios_nsca_command=>"/usr/sbin/send_nsca -H xxx.xxx.xxx -p 5667 -d ~ -c /etc/nagios/send_nsca.cfg", :missed_event=>#<LogStash::Event:0x805d06a @metadata_accessors=#<LogStash::Util::Accessors:0x2d878448

**Comment by jlintz** [comment] 2015-11-13 02:28
Any other info needed?

**Comment by nnebojsa** [comment] 2015-11-14 01:36
I have the same issue and did some test with the log output:
sending :  
echo "NSCA_HOST~NSCA_pre~0~OK" |/usr/sbin/send_nsca -H 172.30.10.11 -p 5667 -d ~ -c /etc/nagios/send_nsca.cfg
can etablish a connection to nsca server but send no data, but sending:
echo "NSCA_HOST~NSCA_pre~0~OK" |/usr/sbin/send_nsca -H 172.30.10.11 -p 5667 -d "~" -c /etc/nagios/send_nsca.cfg
work well. It connect the nsca server and send the output.
Seems a problem with the tilde delimeter.

**Comment by nnebojsa** [comment] 2015-11-23 20:18
[nagios_nsca.rb.txt](https://github.com/logstash-plugins/logstash-output-nagios/files/41979/nagios_nsca.rb.txt)
it's now working for me. I uploaded my file with the changes.

OS:CentOS release 6.4
logstash: logstash 2.0.0
nagios_nsca: 2.0.2

Changes are in lines:

#107, send_nsca have a problem with ~ (tilde) delimeter without double-quotes, changed to ":" (I have no need for the timestamp (with ":" delimeter) in my nagios message)

#109, change ~ against : in the variable message

#114, extend the function call 
send_to_nagios(cmd) to send_to_nagios(cmd, message). 
That is the reason for the message :error=>#<NameError: undefined local variable or method `message' for #<LogStash::Outputs::NagiosNsca:0x47c3b01f>> in the log file

#131 extend the function definition 
def send_to_nagios(cmd) to   def send_to_nagios(cmd, message)

after them build and install:
gem build logstash-output-nagios_nsca.gemspec
/opt/logstash/bin/plugin install logstash-output-nagios_nsca-2.0.2.gem

**Comment by purbon** [comment] 2015-11-24 11:21
@nnebojsa can yo do a PR with this changes? this would be very nice of you. Then we can make sure this plugins works for everyone.

**Comment by tearsakura** [comment] 2015-11-24 15:34
@nnebojsa  @purbon  it works for me too !!! a lot of thanks!!!

OS:Red Hat Enterprise Linux Server release 6.7 (Santiago)
Docker: Imagebase logstash 2.00
logstash: logstash 2.0.0
nagios_nsca: 2.0.2

**Comment by nnebojsa** [comment] 2015-11-25 01:48
already done!

**Comment by purbon** [comment] 2015-11-25 08:09
Fixed in https://github.com/logstash-plugins/logstash-output-nagios_nsca/commit/fd0b85152f4b1f6925c206da074b65bcfbeca4e4 , closing this issue.

**Closed as completed by purbon** 2015-11-25 08:09 UTC
Labels: bug, needs details
